### ISSUE TITLE
Combine AWS Control Tower and AWS Security Hu

### ISSUE THREAD

**Issue by JunaidGH** [awslabs/aws-securityhub-multiaccount-scripts#25]
Hi, 

Thanks for uploading the script. 

I am trying to implement you scripts into our AWS Control Tower setup, which has the following accounts - Master, Audit and Log.  I was wondering if it is possible to get the script to work with having the Audit account as being the primary account, rather than Master Account.  
I am trying to combine AWS Control Tower & AWS Security Hub and use the Audit account as the Security account for AWS Cloutrail, Config, GuardDuty etc...

Thanks

**Comment by ryanholland** [comment]
The Security Hub Master can be any account within the organization and does not have to be the Organization Master, the Security Hub Master/Member only pertains to the Security Hub service. So in the command line provide the account number of your Audit account as the master to have it be your Security Hub Master.

**Comment by JunaidGH** [comment]
Thanks Ryan, i tried that, but originally this was not working and i assumed i was doing something wrong in the script/CLI.  It transpired, it was ControlTower GuardRails which was blocking the permission to create the resources.  

Just wondered is there a reason why:

1) AWS Config is not enabled on the MASTER account were Security Hub is centralised for the rest of the accounts.  When you login to Security Hub is complains saying "AWS Config is not enabled on some accounts"
2) AWS Config logs are not centralised to the MASTER account were Security Hub - configured.  Wouldn't that be better practise and there is an option in AWS Config to perform this steps.  Could be a possibility for a feature-update.

Thanks

**Comment by phancox** [comment]
@JunaidGH would you mind sharing which of the guard rails was causing the problem.
