### ISSUE TITLE
'arn:aws:securityhub:::pci-aws-/v/3.2.1'

### ISSUE THREAD

**Issue by martinklie** [awslabs/aws-securityhub-multiaccount-scripts#26]
Can we support the new PCI compliance?

InvalidInputException(u'An error occurred (InvalidInputException) when calling the BatchEnableStandards operation: Invalid StandardsSubscriptionRequest(s): [{"StandardsArn":"arn:aws:securityhub::pci-aws-/v/3.2.1"}]',)

**Comment by martinklie** [comment]
InvalidInputException(u'An error occurred (InvalidInputException) when calling the BatchEnableStandards operation: Invalid StandardsSubscriptionRequest(s): [{"StandardsArn":"arn:aws:securityhub:::ruleset/pci-dss/v/3.2.1"}]',)

**Comment by martinklie** [comment]
FYI the below worked butas we pass the variable --enabled_regions it would be prefered if the ARN could use this as a variable in its name

arn:aws:securityhub:us-east-2::standards/pci-dss/v/3.2.1

**Comment by ryanholland** [comment]
We have updated the script to have support for the PCI standard.

**Comment by JunaidGH** [comment]
Tried the new script and getting the following issues:

./enablesecurityhub.py --master_account  1234617850610  --assume_role ManageSecurityHub --enabled_regions eu-west-3 enableAudit.csv 

Enabling members in these regions: ['eu-west-3']
Assumed session for 1234617850610.
Beginning 123456789125 in eu-west-3
Traceback (most recent call last):
  File "./enablesecurityhub.py", line 300, in <module>
    sh_client.batch_enable_standards(StandardsSubscriptionRequests=batch_enable_standards_input)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 559, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 607, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter StandardsSubscriptionRequests, value: 0, valid range: 1-inf
