### ISSUE TITLE
AWS Foundational Security Best Practices controls

### ISSUE THREAD

**Issue by martinklie** [awslabs/aws-securityhub-multiaccount-scripts#38]
Any updates needed to enable https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html

As well can we please share the syntax to enable.  Thanks in advanced.

**Comment by bootswithdefer** [comment]
I am using this and it seems to work for me:
`./enablesecurityhub.py --master_account 11111111111 --assume_role AdministratorAccess --enabled_regions us-east-1,us-east-2 --enable_standards arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0,standards/aws-foundational-security-best-practices/v/1.0.0 accounts.csv`

Note the new rule set doesn't need the arn:aws:securityhub prefix.

**Comment by ryanholland** [comment]
Correct the script is setup such that no updates are required for new standards, for all those expect the CIS benchmarks the format is standards/<standard name>/v/x.y.z

**Comment by martinklie** [comment]
If its already enabled running the above will not **ENABLE** the new standard.  Ran the below

/home/ssm-user/aws-securityhub-multiaccount-scripts/enablesecurityhub.py --master_account 11111111111 --assume_role guardduty_sechub --enabled_regions us-east-1 --enable_standards arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0,standards/pci-dss/v/3.2.1 /home/ssm-user/input.csv

and still receive the below pop up windows in each account/region already running Security Hub.

**Introducing AWS Foundational Security Best Practices

The AWS Foundational Security Best Practices standard is a set of automated security checks that detect when AWS accounts and deployed resources do not align with security best practices. The standard is defined by AWS security experts. This curated set of controls helps improve a customer’s security posture in AWS, and covers AWS’s most popular and foundational services. Security Hub recommends that customers enable this standard in all accounts and regions.
New controls
31
Services covered
18
AWS resources
15

Cancel  Enable standard**
