### ISSUE TITLE
Script exits on enabled accounts

### ISSUE THREAD

**Issue by apalooza1** [awslabs/aws-securityhub-multiaccount-scripts#8]
If the script reads in an account that already has security hub enabled, it will automatically exit. Ideally, it should skip to the next line/account in the csv until the list is exhausted.

**Comment by ryanholland** [comment]
The script does not exit on this condition but rather does as you have suggested and first tries to add it as a member and then moves on to the next account.

**Comment by apalooza1** [comment]
I tested where the first account in my list was already enabled. The script did not go on to the 2nd and 3rd accounts in the list. Thoughts?

**Comment by ryanholland** [comment]
Ensure you have one account,email per line in your file also make sure there are no control characters.

**Comment by apalooza1** [comment]
After retesting several times, functionality seems to be as expected. Not sure what happened on the first run. Thanks.
